// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol/login.proto

package pb

/*
pkg:1
*/

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// msg:LoginS2CNotify=0
type LoginS2CNotify struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginS2CNotify) Reset()         { *m = LoginS2CNotify{} }
func (m *LoginS2CNotify) String() string { return proto.CompactTextString(m) }
func (*LoginS2CNotify) ProtoMessage()    {}
func (*LoginS2CNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_login_4ce070741f9ef11a, []int{0}
}
func (m *LoginS2CNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginS2CNotify.Unmarshal(m, b)
}
func (m *LoginS2CNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginS2CNotify.Marshal(b, m, deterministic)
}
func (dst *LoginS2CNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginS2CNotify.Merge(dst, src)
}
func (m *LoginS2CNotify) XXX_Size() int {
	return xxx_messageInfo_LoginS2CNotify.Size(m)
}
func (m *LoginS2CNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginS2CNotify.DiscardUnknown(m)
}

var xxx_messageInfo_LoginS2CNotify proto.InternalMessageInfo

func (m *LoginS2CNotify) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

// msg:LoginC2SLogin=1
type LoginC2SLogin struct {
	Accname              string   `protobuf:"bytes,1,opt,name=accname,proto3" json:"accname,omitempty"`
	Platform             string   `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	Key                  string   `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Token                string   `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	Timestamp            uint32   `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Deviceid             string   `protobuf:"bytes,6,opt,name=deviceid,proto3" json:"deviceid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginC2SLogin) Reset()         { *m = LoginC2SLogin{} }
func (m *LoginC2SLogin) String() string { return proto.CompactTextString(m) }
func (*LoginC2SLogin) ProtoMessage()    {}
func (*LoginC2SLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_login_4ce070741f9ef11a, []int{1}
}
func (m *LoginC2SLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginC2SLogin.Unmarshal(m, b)
}
func (m *LoginC2SLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginC2SLogin.Marshal(b, m, deterministic)
}
func (dst *LoginC2SLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginC2SLogin.Merge(dst, src)
}
func (m *LoginC2SLogin) XXX_Size() int {
	return xxx_messageInfo_LoginC2SLogin.Size(m)
}
func (m *LoginC2SLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginC2SLogin.DiscardUnknown(m)
}

var xxx_messageInfo_LoginC2SLogin proto.InternalMessageInfo

func (m *LoginC2SLogin) GetAccname() string {
	if m != nil {
		return m.Accname
	}
	return ""
}

func (m *LoginC2SLogin) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *LoginC2SLogin) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *LoginC2SLogin) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginC2SLogin) GetTimestamp() uint32 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *LoginC2SLogin) GetDeviceid() string {
	if m != nil {
		return m.Deviceid
	}
	return ""
}

type PLoginInfo struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PLoginInfo) Reset()         { *m = PLoginInfo{} }
func (m *PLoginInfo) String() string { return proto.CompactTextString(m) }
func (*PLoginInfo) ProtoMessage()    {}
func (*PLoginInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_login_4ce070741f9ef11a, []int{2}
}
func (m *PLoginInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PLoginInfo.Unmarshal(m, b)
}
func (m *PLoginInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PLoginInfo.Marshal(b, m, deterministic)
}
func (dst *PLoginInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PLoginInfo.Merge(dst, src)
}
func (m *PLoginInfo) XXX_Size() int {
	return xxx_messageInfo_PLoginInfo.Size(m)
}
func (m *PLoginInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PLoginInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PLoginInfo proto.InternalMessageInfo

func (m *PLoginInfo) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PLoginInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// msg:LoginS2CLogin=2
type LoginS2CLogin struct {
	Code                 uint32      `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	LoginInfo            *PLoginInfo `protobuf:"bytes,2,opt,name=login_info,json=loginInfo,proto3" json:"login_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *LoginS2CLogin) Reset()         { *m = LoginS2CLogin{} }
func (m *LoginS2CLogin) String() string { return proto.CompactTextString(m) }
func (*LoginS2CLogin) ProtoMessage()    {}
func (*LoginS2CLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_login_4ce070741f9ef11a, []int{3}
}
func (m *LoginS2CLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginS2CLogin.Unmarshal(m, b)
}
func (m *LoginS2CLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginS2CLogin.Marshal(b, m, deterministic)
}
func (dst *LoginS2CLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginS2CLogin.Merge(dst, src)
}
func (m *LoginS2CLogin) XXX_Size() int {
	return xxx_messageInfo_LoginS2CLogin.Size(m)
}
func (m *LoginS2CLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginS2CLogin.DiscardUnknown(m)
}

var xxx_messageInfo_LoginS2CLogin proto.InternalMessageInfo

func (m *LoginS2CLogin) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *LoginS2CLogin) GetLoginInfo() *PLoginInfo {
	if m != nil {
		return m.LoginInfo
	}
	return nil
}

// msg:LoginC2SHeartBeat=3
type LoginC2SHeartBeat struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginC2SHeartBeat) Reset()         { *m = LoginC2SHeartBeat{} }
func (m *LoginC2SHeartBeat) String() string { return proto.CompactTextString(m) }
func (*LoginC2SHeartBeat) ProtoMessage()    {}
func (*LoginC2SHeartBeat) Descriptor() ([]byte, []int) {
	return fileDescriptor_login_4ce070741f9ef11a, []int{4}
}
func (m *LoginC2SHeartBeat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginC2SHeartBeat.Unmarshal(m, b)
}
func (m *LoginC2SHeartBeat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginC2SHeartBeat.Marshal(b, m, deterministic)
}
func (dst *LoginC2SHeartBeat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginC2SHeartBeat.Merge(dst, src)
}
func (m *LoginC2SHeartBeat) XXX_Size() int {
	return xxx_messageInfo_LoginC2SHeartBeat.Size(m)
}
func (m *LoginC2SHeartBeat) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginC2SHeartBeat.DiscardUnknown(m)
}

var xxx_messageInfo_LoginC2SHeartBeat proto.InternalMessageInfo

// msg:LoginS2CHeartBeat=4
type LoginS2CHeartBeat struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginS2CHeartBeat) Reset()         { *m = LoginS2CHeartBeat{} }
func (m *LoginS2CHeartBeat) String() string { return proto.CompactTextString(m) }
func (*LoginS2CHeartBeat) ProtoMessage()    {}
func (*LoginS2CHeartBeat) Descriptor() ([]byte, []int) {
	return fileDescriptor_login_4ce070741f9ef11a, []int{5}
}
func (m *LoginS2CHeartBeat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginS2CHeartBeat.Unmarshal(m, b)
}
func (m *LoginS2CHeartBeat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginS2CHeartBeat.Marshal(b, m, deterministic)
}
func (dst *LoginS2CHeartBeat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginS2CHeartBeat.Merge(dst, src)
}
func (m *LoginS2CHeartBeat) XXX_Size() int {
	return xxx_messageInfo_LoginS2CHeartBeat.Size(m)
}
func (m *LoginS2CHeartBeat) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginS2CHeartBeat.DiscardUnknown(m)
}

var xxx_messageInfo_LoginS2CHeartBeat proto.InternalMessageInfo

func init() {
	proto.RegisterType((*LoginS2CNotify)(nil), "pb.LoginS2CNotify")
	proto.RegisterType((*LoginC2SLogin)(nil), "pb.LoginC2SLogin")
	proto.RegisterType((*PLoginInfo)(nil), "pb.p_login_info")
	proto.RegisterType((*LoginS2CLogin)(nil), "pb.LoginS2CLogin")
	proto.RegisterType((*LoginC2SHeartBeat)(nil), "pb.LoginC2SHeartBeat")
	proto.RegisterType((*LoginS2CHeartBeat)(nil), "pb.LoginS2CHeartBeat")
}

func init() { proto.RegisterFile("protocol/login.proto", fileDescriptor_login_4ce070741f9ef11a) }

var fileDescriptor_login_4ce070741f9ef11a = []byte{
	// 275 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x4f, 0x4f, 0xb3, 0x40,
	0x10, 0xc6, 0x03, 0xfd, 0xf3, 0xbe, 0x8c, 0xb6, 0xa9, 0x63, 0x0f, 0x1b, 0xe3, 0xc1, 0x10, 0x0f,
	0x9e, 0x68, 0xb2, 0x7e, 0x03, 0xb9, 0x68, 0x62, 0x3c, 0x80, 0xf7, 0x66, 0x81, 0xc5, 0x6c, 0x0a,
	0xcc, 0x06, 0x37, 0x26, 0xfd, 0x44, 0x7e, 0x4d, 0xc3, 0x6c, 0xa1, 0x1e, 0x3c, 0xf1, 0x3c, 0x3f,
	0x66, 0x77, 0xe6, 0x99, 0x85, 0xad, 0xed, 0xc9, 0x51, 0x49, 0xcd, 0xae, 0xa1, 0x0f, 0xd3, 0x25,
	0x6c, 0x31, 0xb4, 0x45, 0x7c, 0x0f, 0xeb, 0xd7, 0x01, 0xe5, 0x32, 0x7d, 0x23, 0x67, 0xea, 0x23,
	0x22, 0xcc, 0x4b, 0xaa, 0xb4, 0x08, 0xee, 0x82, 0x87, 0x55, 0xc6, 0x3a, 0xfe, 0x0e, 0x60, 0xc5,
	0x65, 0xa9, 0xcc, 0xf9, 0x8b, 0x02, 0xfe, 0xa9, 0xb2, 0xec, 0x54, 0xeb, 0x0b, 0xa3, 0x6c, 0xb4,
	0x78, 0x03, 0xff, 0x6d, 0xa3, 0x5c, 0x4d, 0x7d, 0x2b, 0x42, 0xfe, 0x35, 0x79, 0xdc, 0xc0, 0xec,
	0xa0, 0x8f, 0x62, 0xc6, 0x78, 0x90, 0xb8, 0x85, 0x85, 0xa3, 0x83, 0xee, 0xc4, 0x9c, 0x99, 0x37,
	0x78, 0x0b, 0x91, 0x33, 0xad, 0xfe, 0x74, 0xaa, 0xb5, 0x62, 0xc1, 0x83, 0x9c, 0xc1, 0xd0, 0xa1,
	0xd2, 0x5f, 0xa6, 0xd4, 0xa6, 0x12, 0x4b, 0xdf, 0x61, 0xf4, 0xb1, 0x84, 0x4b, 0xbb, 0xe7, 0x90,
	0x7b, 0xd3, 0xd5, 0x84, 0x6b, 0x08, 0x4d, 0x75, 0xca, 0x12, 0x9a, 0x6a, 0x48, 0xc7, 0x43, 0xfb,
	0xc9, 0x58, 0xc7, 0xef, 0xa7, 0x70, 0xb9, 0x4c, 0x7d, 0xb8, 0x3f, 0x56, 0x80, 0x3b, 0x80, 0xf3,
	0xb5, 0x7c, 0xfc, 0x42, 0x6e, 0x12, 0x5b, 0x24, 0xbf, 0xdb, 0x65, 0x11, 0xeb, 0x97, 0xae, 0xa6,
	0xf8, 0x1a, 0xae, 0xc6, 0x95, 0x3d, 0x6b, 0xd5, 0xbb, 0x27, 0xad, 0xdc, 0x04, 0x73, 0x99, 0x4e,
	0xb0, 0x58, 0xf2, 0x73, 0x3c, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0x90, 0xc8, 0xb2, 0xf6, 0xa6,
	0x01, 0x00, 0x00,
}
