//Code generated by genProtoID. DO NOT EDIT
package pb
const (
ModLoginS2CNotify uint32 =256 // 1-0
ModLoginC2SLogin uint32 =257 // 1-1
ModLoginS2CLogin uint32 =258 // 1-2
ModLoginC2SHeartBeat uint32 =259 // 1-3
ModLoginS2CHeartBeat uint32 =260 // 1-4
)
